development:
  adapter: postgresql
  database: my_images_dev
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_images_test
  pool: 5
  timeout: 5000

production:
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://localhost/my-images") %>
